# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: baptize 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "baptize"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Troels Knak-Nielsen"]
  s.date = "2016-01-05"
  s.description = "Baptize is an extension for Capistrano, that allows for server provisioning"
  s.email = ["troels@knak-nielsen.dk"]
  s.executables = ["baptize"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "lib/baptize.rb",
    "lib/baptize/application.rb",
    "lib/baptize/dsl.rb",
    "lib/baptize/execution_scope.rb",
    "lib/baptize/package_definition.rb",
    "lib/baptize/plugins/apt.rb",
    "lib/baptize/plugins/env.rb",
    "lib/baptize/plugins/execution.rb",
    "lib/baptize/plugins/variables.rb",
    "lib/baptize/plugins/verifications.rb",
    "lib/baptize/rake.rb",
    "lib/baptize/registry.rb",
    "lib/baptize/verification_failure.rb",
    "lib/baptize/version.rb"
  ]
  s.homepage = "http://github.com/troelskn/baptize"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Baptize is an extension for Capistrano, that allows for server provisioning"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, ["~> 3.4"])
      s.add_runtime_dependency(%q<jeweler>, ["~> 2.0"])
    else
      s.add_dependency(%q<capistrano>, ["~> 3.4"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<capistrano>, ["~> 3.4"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
  end
end

