# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "baptize"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Troels Knak-Nielsen"]
  s.date = "2013-09-06"
  s.description = "Baptize is an extension for Capistrano, that allows for server provisioning"
  s.email = ["troels@knak-nielsen.dk"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "lib/baptize.rb",
    "lib/baptize/dsl.rb",
    "lib/baptize/helpers.rb",
    "lib/baptize/install.rb",
    "lib/baptize/plugins/apt.rb",
    "lib/baptize/plugins/base.rb",
    "lib/baptize/plugins/pecl.rb",
    "lib/baptize/plugins/transfer.rb"
  ]
  s.homepage = "http://github.com/troelskn/baptize"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Baptize is an extension for Capistrano, that allows for server provisioning"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 0"])
    else
      s.add_dependency(%q<capistrano>, [">= 0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 0"])
  end
end

